### ISSUE TITLE
Build failures under Go 1.18 due to js.Wrapper removal

### ISSUE THREAD

**Issue by ralimi** [norunners/vert#16]
js.Wrapper was removed in Go 1.18.  Thus, this library fails to build under Go 1.18 due to e.g., https://github.com/norunners/vert/blob/main/value.go#L30.

See https://github.com/golang/go/issues/50310 for some additional background; the proposal to reinstate it was declined.

**Comment by nitram509** [comment]
Fix available in #19

**Comment by norunners** [comment]
Thank you for the contribution, I reviewed the pull request.
